[package]
name = "into_static_str"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Procedural macro for rs-event-emitter"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
